### ISSUE TITLE
Clarification of options for usage of Main.py

### ISSUE THREAD

**Issue by vinaysp** [harveyslash/TSNE-UMAP-Embedding-Visualisation#2]
Hi,

Could you please confirm;
-what type of raw data should be put in the data folder e.g. raw images or numpy array etc. 
-name, is this a name that I am assigning for the new visualisation?
- model_input_size, is there a specific number that should be used what does this usage option actually do?

sorry for the silly questions but just want to make sure that i am using the embedding-visualiser correctly.

Thanks.

**Comment by harveyslash** [comment]
1. Raw images should be used
2. Yes 
3. This is the resolution of the image that the model will be working with. Some models in the model zoo require a particular input size, which is why this option exists
