### ISSUE TITLE
Selection and Distances don't seem to work

### ISSUE THREAD

**Issue by mohammedayub44** [harveyslash/TSNE-UMAP-Embedding-Visualisation#4]
Hi @harveyslash  
First of all thanks for giving detailed documentation to this project, it's really helpful. I'm trying to replicate this on my localhost:8000 without any changes.  I'm wondering why the selections (click actions on the sprites images) functionality doesn't seem to work. I don't get any error while hosting as well. 

Anyway to troubleshoot this. Any help appreciated.

Mohammed Ayub

**Comment by harveyslash** [comment]
Unfortunately, the projector mechanic itself is now part of this project. If you can tell me the process to reproduce the problem, I may file a bug at the projector project.
